PREPROCESSING:
  gaussian_blur_kernel_size: [3, 3]
  gaussian_blur_sigma: 0

  clahe_clip_limit: 2.0
  clahe_tile_grid_size: [8, 8]

  gaussian_filter_sigma: 15

  remove_small_objects_min_size: 150
  remove_small_holes_area_threshold: 150

  border_size_noise_removal: 3

CENTROIDS_POINTS_AND_BBOXES:
  area_threshold_touching_cells: 750

  touching_cells_neighborhood_size: 14

CONTOUR_AND_BACKGROUND_POINTS:

  get_cell_contour_points_max_sigma: 1
  get_cell_contour_points_threshold: 0

  get_background_points_min_distance: 4
  get_background_points_threshold_abs: 25

SAM2:
  sam2_checkpoint: "segment-anything-2\checkpoints\sam2_hiera_large.pt"
  sam2_model_config: "sam2_hiera_l.yaml"
  multimask_output: True
  use_sam2_postprocessing: True